theme: jekyll-theme-slate
name: Utilizing AutoPhrase on Computer Science papers over time
description: Cameron Brody, Jason Lin, James Yu
title: Utilizing AutoPhrase on Computer Science papers over time
